
version: "3.8"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      # from local to docker
      - "8000:8000"
    volumes:
      - ./app:/app
    command:
      sh -c "python manage.py runserver 0.0.0.0:8000"
